django_Generel_project/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static

from mysite.home import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include("mysite.authentication.urls")), # Auth routes - login / register

    path('car/', include('mysite.car.urls')),  # подключение приложения
    path('helicopter/', include('mysite.helicopter.urls')),  # подключение приложения
    path('anketa/', include('mysite.anketa.urls')),  # подключение приложения
    path('testik/', include('mysite.testik.urls')),  # подключение приложения

                  # Leave `Home.Urls` as last the last line
                  # Leave `Home.Urls` as last the last line НЕ УДАЛЯТЬ $ КАК БЫ СИЛЬНО НИ ХОТЕЛОСЬ
                  # удаление этой штуки влечет за собой изменение ссылок на скачивание всех файлов
    re_path("^$", include("mysite.home.urls")),


    path('<str:template_name>.html/', views.static_html, name='temp_html')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_Generel_project/mysite/testik/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static

from mysite.testik.views import *
from mysite.home import views
app_name = 'testik'
urlpatterns = [
    #path('admin/', admin.site.urls),
    path('otvet/', OtvetView.as_view(), name='Otvet'),
    path('otvet/update/<int:pk>/', OtvetUpdate.as_view(), name='OtvetUpdate'),
    path('otvet/detail/<int:pk>/', OtvetDetail.as_view(), name='OtvetDetail'),
    path('otvet/create/', OtvetCreate.as_view(), name='OtvetCreate'),
    path('otvet/delete/<int:pk>/', OtvetDelete.as_view(), name='OtvetDelete'),

    path('sertif/', SertifView.as_view(), name='Sertif'),
    path('sertif/update/<int:pk>/', SertifUpdate.as_view(), name='SertifUpdate'),
    path('sertif/detail/<int:pk>/', SertifDetail.as_view(), name='SertifDetail'),
    path('sertif/create/', SertifCreate.as_view(), name='SertifCreate'),
    path('sertif/delete/<int:pk>/', SertifDelete.as_view(), name='SertifDelete'),
]

django_Generel_project/mysite/testik/models.py
from django.contrib.auth.models import User
from django.db import models

from mysite.anketa.models import Naviki, Sertifikat, Grazhdanin


# Create your models here.


class Otvet(models.Model):
    polzovatel = models.ForeignKey(Grazhdanin, on_delete=models.PROTECT, verbose_name="Пользователь")
    navik = models.ForeignKey(Naviki, on_delete=models.PROTECT, verbose_name="Навык")
    ball = models.IntegerField(blank=True, null=True, default='0', verbose_name="Баллы")
    data = models.DateTimeField(verbose_name="Дата")

    class Meta:
        ordering = ["-id"]
        verbose_name = "Ответ"
        verbose_name_plural = "Ответ"

    def __str__(self):
        return self.polzovatel

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in Otvet._meta.fields]


class Sertif(models.Model):
    sertif = models.ForeignKey(Sertifikat, on_delete=models.PROTECT, verbose_name="Сертификат")
    polzovatel = models.ForeignKey(Grazhdanin, on_delete=models.PROTECT, verbose_name="Пользователь")
    osnnavik = models.IntegerField(blank=True, null=True, default='0', verbose_name="Основной навык")
    vsenavik = models.IntegerField(blank=True, null=True, default='0', verbose_name="Все навыки")
    data = models.DateTimeField(verbose_name="Дата")
    itog = models.FileField(max_length=255, verbose_name="Сертификат")

    class Meta:
        ordering = ["-polzovatel"]
        verbose_name = "Сертификат"
        verbose_name_plural = "Сертификаты"

    def __str__(self):
        return self.itog

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in Sertif._meta.fields]

django_Generel_project/mysite/testik/views/otvet.py
#!/usr/bin/env python
# -*- coding: utf8 -*-
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, UpdateView, DetailView, CreateView, DeleteView
from mysite.testik.models import *
item_for_page = 15

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class OtvetView(ListView):
    model = Otvet
    context_object_name = 'otvet_list'
    success_url = reverse_lazy('testik: Otvet')

    paginate_by = item_for_page
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(OtvetView,self).get_context_data(**kwargs)
        context['sometry'] = self.model._meta.verbose_name_plural
        context['col1name'] = self.model._meta.get_field("polzovatel").verbose_name
        context['col2name'] = self.model._meta.get_field("navik").verbose_name
        context['col3name'] = self.model._meta.get_field("ball").verbose_name
        context['col4name'] = self.model._meta.get_field("data").verbose_name

        context['collastname'] = 'Сервисы'
        return context


@method_decorator(login_required(login_url='/login/'), name='dispatch')
class OtvetUpdate(UpdateView):
    model = Otvet
    template_name_suffix = '_update_form'
    fields = '__all__'
    success_url = '/testik/otvet/'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(OtvetUpdate,self).get_context_data(**kwargs)
        context['sometry'] = self.model._meta.verbose_name
        context['slovar'] = {'prof','navik'}
        context['secslovar'] = {'ball','data'}
        context['hidenslovar'] = {'id'}
        context['dopslovar'] = {'edesc','updated_at','updated_it','created_it','created_at','erem'}
        context['model'] = self.model
        return context

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class OtvetDetail(DetailView):
    model = Otvet
    context_object_name = 'otvet_one'
    success_url = '/testik/otvet/'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(OtvetDetail,self).get_context_data(**kwargs)
        context['sometry'] = self.model._meta.verbose_name
        context['slovar'] = {'prof','navik'}
        context['secslovar'] = {'ball','data'}
        context['hidenslovar'] = {'id'}
        context['dopslovar'] = {'edesc','updated_at','updated_it','created_it','created_at','erem'}
        context['model'] = self.model
        return context

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class OtvetCreate(CreateView):
    model = Otvet
    context_object_name = 'otvet_one'
    success_url = '/testik/otvet/'

    template_name_suffix = '_create_form'
    fields = '__all__'
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(OtvetCreate,self).get_context_data(**kwargs)
        context['sometry'] = self.model._meta.verbose_name
        context['model'] = self.model
        context['slovar'] = {'prof','navik'}
        context['secslovar'] = {'ball','data'}
        context['hidenslovar'] = {'id'}
        context['dopslovar'] = {'edesc','updated_at','updated_it','created_it','created_at','erem'}
        return context

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class OtvetDelete(DeleteView):
    model = Otvet
    success_url = '/testik/otvet/'

django_Generel_project/mysite/testik/views/sertif.py
#!/usr/bin/env python
# -*- coding: utf8 -*-
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, UpdateView, DetailView, CreateView, DeleteView
from mysite.testik.models import *
item_for_page = 15

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class SertifView(ListView):
    model = Sertif
    context_object_name = 'sertif_list'
    success_url = reverse_lazy('testik: Sertif')

    paginate_by = item_for_page
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(SertifView,self).get_context_data(**kwargs)
        context['sometry'] = self.model._meta.verbose_name_plural
        context['col1name'] = self.model._meta.get_field("sertif").verbose_name
        context['col2name'] = self.model._meta.get_field("polzovatel").verbose_name
        context['col3name'] = self.model._meta.get_field("osnnavik").verbose_name
        context['col4name'] = self.model._meta.get_field("vsenavik").verbose_name
        context['col5name'] = self.model._meta.get_field("data").verbose_name
        context['col6name'] = self.model._meta.get_field("itog").verbose_name

        context['collastname'] = 'Сервисы'
        return context


@method_decorator(login_required(login_url='/login/'), name='dispatch')
class SertifUpdate(UpdateView):
    model = Sertif
    template_name_suffix = '_update_form'
    fields = '__all__'
    success_url = '/testik/sertif/'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(SertifUpdate,self).get_context_data(**kwargs)
        context['sometry'] = self.model._meta.verbose_name
        context['slovar'] = {'polzovatel','osnnavik','sertif'}
        context['secslovar'] = {'data','vsenavik','itog'}
        context['hidenslovar'] = {'id'}
        context['dopslovar'] = {'edesc','created_at','created_it','erem','updated_at','updated_it'}
        context['model'] = self.model
        return context

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class SertifDetail(DetailView):
    model = Sertif
    context_object_name = 'sertif_one'
    success_url = '/testik/sertif/'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(SertifDetail,self).get_context_data(**kwargs)
        context['sometry'] = self.model._meta.verbose_name
        context['slovar'] = {'polzovatel','osnnavik','sertif'}
        context['secslovar'] = {'data','vsenavik','itog'}
        context['hidenslovar'] = {'id'}
        context['dopslovar'] = {'edesc','created_at','created_it','erem','updated_at','updated_it'}
        context['model'] = self.model
        return context

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class SertifCreate(CreateView):
    model = Sertif
    context_object_name = 'sertif_one'
    success_url = '/testik/sertif/'

    template_name_suffix = '_create_form'
    fields = '__all__'
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(SertifCreate,self).get_context_data(**kwargs)
        context['sometry'] = self.model._meta.verbose_name
        context['model'] = self.model
        context['slovar'] = {'polzovatel','osnnavik','sertif'}
        context['secslovar'] = {'data','vsenavik','itog'}
        context['hidenslovar'] = {'id'}
        context['dopslovar'] = {'edesc','created_at','created_it','erem','updated_at','updated_it'}
        return context

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class SertifDelete(DeleteView):
    model = Sertif
    success_url = '/testik/sertif/'

django_Generel_project/mysite/testik/views/views_help.py
from django.shortcuts import render

# Create your views here.

django_Generel_project/mysite/testik/templates/testik/otvet_confirm_delete.html
{% extends 'testik/base.html' %}
{% load testik_tags %}
{% block content %}

    <div class="content-wrapper">
            <!-- Content Header (Page header) -->
    {% block sidebar %}
    {% include 'testik/includes/_breadcrumb.html' %}
    {% endblock %}

    <section class="content">

    <h2>Удаление</h2>
    <p>Вы точно хотите удалить?</p>
    <form method="post">
        {% csrf_token %}
        <p class="text-danger text-bold"> Удаляется обьект:  "{{ object }}"</p>
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'testik:Otvet' %}" class="btn btn-default">Выйти</a>
    </form>
    </section>
    </div>

{% endblock %}

django_Generel_project/mysite/testik/templates/testik/otvet_create_form.html
{% extends 'testik/base.html' %}
{% load testik_tags %}
{% block content %}




    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        {% block sidebar %}
            {% include 'testik/includes/_breadcrumb.html' %}
        {% endblock %}

        <!-- Main content -->
        <section class="content">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="row">
                    <div class="col-md-6">
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Основные сведения</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                            title="Collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                {% for field in form %}
                                    <div class="form-group">
                                        {% if field.name in slovar %}
                                            {{ field.label_tag }}
                                            {{ field | addclassrow:"form-control " }}
                                            {{ field.errors }}
                                        {% endif %}
                                    </div>
                                {% endfor %}


                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <div class="col-md-6">
                        <div class="card card-secondary">
                            <div class="card-header">
                                <h3 class="card-title">Дополнительные сведения</h3>
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                            title="Collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                {% for field in form %}
                                    <div class="form-group">
                                        {% if field.name in secslovar %}
                                            {{ field.label_tag }}
                                            {{ field | addclassrow:"form-control " }}
                                            {{ field.errors }}
                                        {% endif %}
                                    </div>
                                {% endfor %}

                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->

                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <div class="card card-info collapsed-card">
                            <div class="card-header">
                                <h3 class="card-title">Дополнительная информация</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                            title="Collapse">
                                        <i class="fas fa-plus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                {% for field in form %}
                                    <div class="form-group">
                                        {% if field.name in dopslovar %}
                                            {{ field.label_tag }}
                                            {{ field | addclassrow:"form-control " }}
                                            {{ field.errors }}
                                        {% endif %}

                                    </div>
                                {% endfor %}

                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->

                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <a href="{% url 'testik:Otvet' %}" class="btn btn-secondary float-right">
                            {% my_notsave %}</a>
                        <input type="submit" value="{% my_save %}" class="btn btn-success ">
                    </div>
                </div>
                <!-- /.row -->
            </form>

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
{% endblock content %}

django_Generel_project/mysite/testik/templates/testik/otvet_detail.html
{% extends 'testik/base.html' %}
{% load testik_tags %}
{% block content %}




    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
    {% block sidebar %}
        {% include 'testik/includes/_breadcrumb.html' %}
    {% endblock %}

        <!-- Main content -->
        <section class="content">


            <div class="col-md-10">

                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Наименование</th>
                        <th scope="col">Значение</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for name, value in otvet_one.get_fields %}
                        {% if name in slovar %}
                            <tr>
                                <td>
                                    {% field_name otvet_one name %}
                                </td>
                                <td>
                                    {{ value |  nonefortext }}
                                </td>
                            </tr>
                        {% endif %}
                     {% if name in secslovar %}
                            <tr>
                                <td>
                                    {% field_name otvet_one name %}
                                </td>
                                <td>
                                    {{ value |  nonefortext }}
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}

                    </tbody>
                </table>

            <a href="{% url 'testik:Otvet' %}" class="btn btn-secondary float-right">
                {% my_comeback %}</a>


            </div>

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
{% endblock content %}

django_Generel_project/mysite/testik/templates/testik/otvet_list.html
{% extends "testik/base.html" %}

{#{% block page_heading %}{% endblock %}#}
{% block title %}{{ sometry }} {% endblock %}

{% block content %}

{% load testik_tags %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">

    <!-- Content Header (Page header) -->
    {% block sidebar %}
    {% include 'testik/includes/_breadcrumb.html' %}
    {% endblock %}

    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <button class="btn bg-success btn-sm">
            <a href="{% url 'testik:OtvetCreate' %}" class=''>
                Добавить новый
            </a>
        </button>
        <br><br>

        <div class="container-fluid row">
            <div class="col-md-12">
                <table class="table table-striped table-bordered ">
                    <tr>
                        <th class="w-25">{{col1name}}</th> <th class="w-25">{{col2name}}</th> <th class="w-25">{{col3name}}</th> <th class="w-25">{{col4name}}</th>
                        <th colspan="3">Сервисы</th>

                    </tr>

                    {% for item in otvet_list %}
                    <tr>
                         <td><h5 class="card-title">{{ item.polzovatel }}</h5></td>  <td><h5 class="card-title">{{ item.navik }}</h5></td>  <td><h5 class="card-title">{{ item.ball }}</h5></td>  <td><h5 class="card-title">{{ item.data }}</h5></td>
                        <td>
                            <button class="btn bg-primary  btn-sm">
                                <a href="{% url 'testik:OtvetUpdate' item.pk %}">Редактировать</a>
                            </button>
                        </td>
                        <td>
                            <button class="btn bg-primary  btn-sm">
                                <a href="{% url 'testik:OtvetDetail' item.pk %}">Подробнее</a>
                            </button>
                        </td>
                        <td>
                            <button class="btn bg-danger  btn-sm" >
                                <a href="{% url 'testik:OtvetDelete' item.pk %}">Удалить</a>
                            </button>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>

        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

{% endblock %}

django_Generel_project/mysite/testik/templates/testik/otvet_update_form.html
{% extends 'testik/base.html' %}
{% load testik_tags %}
{% block content %}




    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        {% block sidebar %}
            {% include 'testik/includes/_breadcrumb.html' %}
        {% endblock %}

        <!-- Main content -->
        <section class="content">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="row">
                    <div class="col-md-6">
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Основные сведения</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                            title="Collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                {% for field in form %}
                                    <div class="form-group">
                                        {% if field.name in slovar %}
                                            {{ field.label_tag }}
                                            {{ field | addclassrow:"form-control " }}
                                            {{ field.errors }}
                                        {% endif %}
                                    </div>
                                {% endfor %}


                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <div class="col-md-6">
                        <div class="card card-secondary">
                            <div class="card-header">
                                <h3 class="card-title">Дополнительные сведения</h3>
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                            title="Collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                {% for field in form %}
                                    <div class="form-group">
                                        {% if field.name in secslovar %}
                                            {{ field.label_tag }}
                                            {{ field | addclassrow:"form-control " }}
                                            {{ field.errors }}
                                        {% endif %}
                                    </div>
                                {% endfor %}

                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->

                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <div class="card card-info collapsed-card">
                            <div class="card-header">
                                <h3 class="card-title">Дополнительная информация</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                            title="Collapse">
                                        <i class="fas fa-plus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                {% for field in form %}
                                    <div class="form-group">
                                        {% if field.name in dopslovar %}
                                            {{ field.label_tag }}
                                            {{ field | addclassrow:"form-control " }}
                                            {{ field.errors }}
                                        {% endif %}

                                    </div>
                                {% endfor %}

                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->

                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <a href="{% url 'testik:Otvet' %}" class="btn btn-secondary float-right">
                            {% my_notsave %}</a>
                        <input type="submit" value="{% my_save %}" class="btn btn-success ">
                    </div>
                </div>
                <!-- /.row -->
            </form>

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
{% endblock content %}

django_Generel_project/mysite/testik/templates/testik/sertif_confirm_delete.html
{% extends 'testik/base.html' %}
{% load testik_tags %}
{% block content %}

    <div class="content-wrapper">
            <!-- Content Header (Page header) -->
    {% block sidebar %}
    {% include 'testik/includes/_breadcrumb.html' %}
    {% endblock %}

    <section class="content">

    <h2>Удаление</h2>
    <p>Вы точно хотите удалить?</p>
    <form method="post">
        {% csrf_token %}
        <p class="text-danger text-bold"> Удаляется обьект:  "{{ object }}"</p>
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'testik:Sertif' %}" class="btn btn-default">Выйти</a>
    </form>
    </section>
    </div>

{% endblock %}

django_Generel_project/mysite/testik/templates/testik/sertif_list.html
{% extends "testik/base.html" %}

{#{% block page_heading %}{% endblock %}#}
{% block title %}{{ sometry }} {% endblock %}

{% block content %}

{% load testik_tags %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">

    <!-- Content Header (Page header) -->
    {% block sidebar %}
    {% include 'testik/includes/_breadcrumb.html' %}
    {% endblock %}

    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <button class="btn bg-success btn-sm">
            <a href="{% url 'testik:SertifCreate' %}" class=''>
                Добавить новый
            </a>
        </button>
        <br><br>

        <div class="container-fluid row">
            <div class="col-md-12">
                <table class="table table-striped table-bordered ">
                    <tr>
                        <th class="w-25">{{col1name}}</th> <th class="w-25">{{col2name}}</th> <th class="w-25">{{col3name}}</th> <th class="w-25">{{col4name}}</th> <th class="w-25">{{col5name}}</th> <th class="w-25">{{col6name}}</th>
                        <th colspan="3">Сервисы</th>

                    </tr>

                    {% for item in sertif_list %}
                    <tr>
                         <td><h5 class="card-title">{{ item.sertif }}</h5></td>  <td><h5 class="card-title">{{ item.polzovatel }}</h5></td>  <td><h5 class="card-title">{{ item.osnnavik }}</h5></td>  <td><h5 class="card-title">{{ item.vsenavik }}</h5></td>  <td><h5 class="card-title">{{ item.data }}</h5></td>  <td><h5 class="card-title">{{ item.itog }}</h5></td>
                        <td>
                            <button class="btn bg-primary  btn-sm">
                                <a href="{% url 'testik:SertifUpdate' item.pk %}">Редактировать</a>
                            </button>
                        </td>
                        <td>
                            <button class="btn bg-primary  btn-sm">
                                <a href="{% url 'testik:SertifDetail' item.pk %}">Подробнее</a>
                            </button>
                        </td>
                        <td>
                            <button class="btn bg-danger  btn-sm" >
                                <a href="{% url 'testik:SertifDelete' item.pk %}">Удалить</a>
                            </button>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>

        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

{% endblock %}