django_Generel_project/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static

from mysite.home import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include("mysite.authentication.urls")), # Auth routes - login / register

    path('car/', include('mysite.car.urls')),  # подключение приложения
    path('helicopter/', include('mysite.helicopter.urls')),  # подключение приложения
    path('anketa/', include('mysite.anketa.urls')),  # подключение приложения
    path('testik/', include('mysite.testik.urls')),  # подключение приложения

                  # Leave `Home.Urls` as last the last line
                  # Leave `Home.Urls` as last the last line НЕ УДАЛЯТЬ $ КАК БЫ СИЛЬНО НИ ХОТЕЛОСЬ
                  # удаление этой штуки влечет за собой изменение ссылок на скачивание всех файлов
    re_path("^$", include("mysite.home.urls")),


    path('<str:template_name>.html/', views.static_html, name='temp_html')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_Generel_project/mysite/anketa/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static

from mysite.anketa.views import *
from mysite.home import views
app_name = 'anketa'
urlpatterns = [
    #path('admin/', admin.site.urls),

    path('proffessia/', ProffessiaView.as_view(), name='Proffessia'),
    path('proffessia/update/<int:pk>/', ProffessiaUpdate.as_view(), name='ProffessiaUpdate'),
    path('proffessia/detail/<int:pk>/', ProffessiaDetail.as_view(), name='ProffessiaDetail'),
    path('proffessia/create/', ProffessiaCreate.as_view(), name='ProffessiaCreate'),
    path('proffessia/delete/<int:pk>/', ProffessiaDelete.as_view(), name='ProffessiaDelete'),

    path('naviki/', NavikiView.as_view(), name='Naviki'),
    path('naviki/update/<int:pk>/', NavikiUpdate.as_view(), name='NavikiUpdate'),
    path('naviki/detail/<int:pk>/', NavikiDetail.as_view(), name='NavikiDetail'),
    path('naviki/create/', NavikiCreate.as_view(), name='NavikiCreate'),
    path('naviki/delete/<int:pk>/', NavikiDelete.as_view(), name='NavikiDelete'),

    path('sertifikat/', SertifikatView.as_view(), name='Sertifikat'),
    path('sertifikat/update/<int:pk>/', SertifikatUpdate.as_view(), name='SertifikatUpdate'),
    path('sertifikat/detail/<int:pk>/', SertifikatDetail.as_view(), name='SertifikatDetail'),
    path('sertifikat/create/', SertifikatCreate.as_view(), name='SertifikatCreate'),
    path('sertifikat/delete/<int:pk>/', SertifikatDelete.as_view(), name='SertifikatDelete'),

    path('voprosi/', VoprosiView.as_view(), name='Voprosi'),
    path('voprosi/update/<int:pk>/', VoprosiUpdate.as_view(), name='VoprosiUpdate'),
    path('voprosi/detail/<int:pk>/', VoprosiDetail.as_view(), name='VoprosiDetail'),
    path('voprosi/create/', VoprosiCreate.as_view(), name='VoprosiCreate'),
    path('voprosi/delete/<int:pk>/', VoprosiDelete.as_view(), name='VoprosiDelete'),

    path('grazhdanin/', GrazhdaninView.as_view(), name='Grazhdanin'),
    path('grazhdanin/update/<int:pk>/', GrazhdaninUpdate.as_view(), name='GrazhdaninUpdate'),
    path('grazhdanin/detail/<int:pk>/', GrazhdaninDetail.as_view(), name='GrazhdaninDetail'),
    path('grazhdanin/create/', GrazhdaninCreate.as_view(), name='GrazhdaninCreate'),
    path('grazhdanin/delete/<int:pk>/', GrazhdaninDelete.as_view(), name='GrazhdaninDelete'),

    path('modelprof/', ModelProfView.as_view(), name='ModelProf'),
    path('modelprof/update/<int:pk>/', ModelProfUpdate.as_view(), name='ModelProfUpdate'),
    path('modelprof/detail/<int:pk>/', ModelProfDetail.as_view(), name='ModelProfDetail'),
    path('modelprof/create/', ModelProfCreate.as_view(), name='ModelProfCreate'),
    path('modelprof/delete/<int:pk>/', ModelProfDelete.as_view(), name='ModelProfDelete'),
]

django_Generel_project/mysite/anketa/views/Grazhdanin.py
#!/usr/bin/env python
# -*- coding: utf8 -*-
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, UpdateView, DetailView, CreateView, DeleteView
from mysite.anketa.models import *
item_for_page = 15

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class GrazhdaninView(ListView):
    model = Grazhdanin
    context_object_name = 'grazhdanin_list'
    success_url = reverse_lazy('anketa: Grazhdanin')

    paginate_by = item_for_page
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(GrazhdaninView,self).get_context_data(**kwargs)
        context['sometry'] = self.model._meta.verbose_name_plural
        context['col1name'] = self.model._meta.get_field("avatar").verbose_name
        context['col2name'] = self.model._meta.get_field("nomer").verbose_name
        context['col3name'] = self.model._meta.get_field("sertific").verbose_name

        context['collastname'] = 'Сервисы'
        return context


@method_decorator(login_required(login_url='/login/'), name='dispatch')
class GrazhdaninUpdate(UpdateView):
    model = Grazhdanin
    template_name_suffix = '_update_form'
    fields = '__all__'
    success_url = '/anketa/grazhdanin/'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(GrazhdaninUpdate,self).get_context_data(**kwargs)
        context['sometry'] = self.model._meta.verbose_name
        context['slovar'] = {'avatar','nomer'}
        context['secslovar'] = {'sertific'}
        context['hidenslovar'] = {'id'}
        context['dopslovar'] = {'created_at','edesc','created_it','updated_it','erem','updated_at'}
        context['model'] = self.model
        return context

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class GrazhdaninDetail(DetailView):
    model = Grazhdanin
    context_object_name = 'grazhdanin_one'
    success_url = '/anketa/grazhdanin/'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(GrazhdaninDetail,self).get_context_data(**kwargs)
        context['sometry'] = self.model._meta.verbose_name
        context['slovar'] = {'avatar','nomer'}
        context['secslovar'] = {'sertific'}
        context['hidenslovar'] = {'id'}
        context['dopslovar'] = {'created_at','edesc','created_it','updated_it','erem','updated_at'}
        context['model'] = self.model
        return context

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class GrazhdaninCreate(CreateView):
    model = Grazhdanin
    context_object_name = 'grazhdanin_one'
    success_url = '/anketa/grazhdanin/'

    template_name_suffix = '_create_form'
    fields = '__all__'
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(GrazhdaninCreate,self).get_context_data(**kwargs)
        context['sometry'] = self.model._meta.verbose_name
        context['model'] = self.model
        context['slovar'] = {'avatar','nomer'}
        context['secslovar'] = {'sertific'}
        context['hidenslovar'] = {'id'}
        context['dopslovar'] = {'created_at','edesc','created_it','updated_it','erem','updated_at'}
        return context

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class GrazhdaninDelete(DeleteView):
    model = Grazhdanin
    success_url = '/anketa/grazhdanin/'

django_Generel_project/mysite/anketa/views/Naviki.py
#!/usr/bin/env python
# -*- coding: utf8 -*-
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, UpdateView, DetailView, CreateView, DeleteView
from mysite.anketa.models import *
item_for_page = 15

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class NavikiView(ListView):
	model = Naviki
	context_object_name = 'naviki_list'
	success_url = reverse_lazy('anketa: Naviki')

	paginate_by = item_for_page
	def get_context_data(self, *, object_list=None, **kwargs):
		context = super(NavikiView,self).get_context_data(**kwargs)
		context['sometry'] = self.model._meta.verbose_name_plural
		context['col1name'] = self.model._meta.get_field("title").verbose_name

		context['collastname'] = 'Сервисы'
		return context


@method_decorator(login_required(login_url='/login/'), name='dispatch')
class NavikiUpdate(UpdateView):
	model = Naviki
	template_name_suffix = '_update_form'
	fields = '__all__'
	success_url = '/anketa/naviki/'

	def get_context_data(self, *, object_list=None, **kwargs):
		context = super(NavikiUpdate,self).get_context_data(**kwargs)
		context['sometry'] = self.model._meta.verbose_name
		context['slovar'] = {'title'}
		context['secslovar'] = {''}
		context['hidenslovar'] = {'id'}
		context['dopslovar'] = {'updated_it','erem','created_it','updated_at','edesc','created_at'}
		context['model'] = self.model
		return context

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class NavikiDetail(DetailView):
	model = Naviki
	context_object_name = 'naviki_one'
	success_url = '/anketa/naviki/'

	def get_context_data(self, *, object_list=None, **kwargs):
		context = super(NavikiDetail,self).get_context_data(**kwargs)
		context['sometry'] = self.model._meta.verbose_name
		context['slovar'] = {'title'}
		context['secslovar'] = {''}
		context['hidenslovar'] = {'id'}
		context['dopslovar'] = {'updated_it','erem','created_it','updated_at','edesc','created_at'}
		context['model'] = self.model
		return context

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class NavikiCreate(CreateView):
	model = Naviki
	context_object_name = 'naviki_one'
	success_url = '/anketa/naviki/'

	template_name_suffix = '_create_form'
	fields = '__all__'
	def get_context_data(self, *, object_list=None, **kwargs):
		context = super(NavikiCreate,self).get_context_data(**kwargs)
		context['sometry'] = self.model._meta.verbose_name
		context['model'] = self.model
		context['slovar'] = {'title'}
		context['secslovar'] = {''}
		context['hidenslovar'] = {'id'}
		context['dopslovar'] = {'updated_it','erem','created_it','updated_at','edesc','created_at'}
		return context

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class NavikiDelete(DeleteView):
	model = Naviki
	success_url = '/anketa/naviki/'

django_Generel_project/mysite/anketa/views/Proffessia.py
#!/usr/bin/env python
# -*- coding: utf8 -*-
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, UpdateView, DetailView, CreateView, DeleteView
from mysite.anketa.models import *
item_for_page = 15

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class ProffessiaView(ListView):
	model = Proffessia
	context_object_name = 'proffessia_list'
	success_url = reverse_lazy('anketa: Proffessia')

	paginate_by = item_for_page
	def get_context_data(self, *, object_list=None, **kwargs):
		context = super(ProffessiaView,self).get_context_data(**kwargs)
		context['sometry'] = self.model._meta.verbose_name_plural
		context['col1name'] = self.model._meta.get_field("title").verbose_name

		context['collastname'] = 'Сервисы'
		return context


@method_decorator(login_required(login_url='/login/'), name='dispatch')
class ProffessiaUpdate(UpdateView):
	model = Proffessia
	template_name_suffix = '_update_form'
	fields = '__all__'
	success_url = '/anketa/proffessia/'

	def get_context_data(self, *, object_list=None, **kwargs):
		context = super(ProffessiaUpdate,self).get_context_data(**kwargs)
		context['sometry'] = self.model._meta.verbose_name
		context['slovar'] = {'title'}
		context['secslovar'] = {''}
		context['hidenslovar'] = {'id'}
		context['dopslovar'] = {'created_at','erem','updated_at','updated_it','edesc','created_it'}
		context['model'] = self.model
		return context

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class ProffessiaDetail(DetailView):
	model = Proffessia
	context_object_name = 'proffessia_one'
	success_url = '/anketa/proffessia/'

	def get_context_data(self, *, object_list=None, **kwargs):
		context = super(ProffessiaDetail,self).get_context_data(**kwargs)
		context['sometry'] = self.model._meta.verbose_name
		context['slovar'] = {'title'}
		context['secslovar'] = {''}
		context['hidenslovar'] = {'id'}
		context['dopslovar'] = {'created_at','erem','updated_at','updated_it','edesc','created_it'}
		context['model'] = self.model
		return context

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class ProffessiaCreate(CreateView):
	model = Proffessia
	context_object_name = 'proffessia_one'
	success_url = '/anketa/proffessia/'

	template_name_suffix = '_create_form'
	fields = '__all__'
	def get_context_data(self, *, object_list=None, **kwargs):
		context = super(ProffessiaCreate,self).get_context_data(**kwargs)
		context['sometry'] = self.model._meta.verbose_name
		context['model'] = self.model
		context['slovar'] = {'title'}
		context['secslovar'] = {''}
		context['hidenslovar'] = {'id'}
		context['dopslovar'] = {'created_at','erem','updated_at','updated_it','edesc','created_it'}
		return context

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class ProffessiaDelete(DeleteView):
	model = Proffessia
	success_url = '/anketa/proffessia/'

django_Generel_project/mysite/anketa/views/modelprof.py
#!/usr/bin/env python
# -*- coding: utf8 -*-
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, UpdateView, DetailView, CreateView, DeleteView
from mysite.anketa.models import *
item_for_page = 15

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class ModelProfView(ListView):
    model = ModelProf
    context_object_name = 'modelprof_list'
    success_url = reverse_lazy('anketa: ModelProf')

    paginate_by = item_for_page
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ModelProfView,self).get_context_data(**kwargs)
        context['sometry'] = self.model._meta.verbose_name_plural
        context['col1name'] = self.model._meta.get_field("prof").verbose_name
        context['col2name'] = self.model._meta.get_field("navik").verbose_name
        context['col3name'] = self.model._meta.get_field("ball").verbose_name

        context['collastname'] = 'Сервисы'
        return context


@method_decorator(login_required(login_url='/login/'), name='dispatch')
class ModelProfUpdate(UpdateView):
    model = ModelProf
    template_name_suffix = '_update_form'
    fields = '__all__'
    success_url = '/anketa/modelprof/'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ModelProfUpdate,self).get_context_data(**kwargs)
        context['sometry'] = self.model._meta.verbose_name
        context['slovar'] = {'prof','navik'}
        context['secslovar'] = {'ball'}
        context['hidenslovar'] = {'id'}
        context['dopslovar'] = {'created_at','updated_at','created_it','updated_it','edesc','erem'}
        context['model'] = self.model
        return context

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class ModelProfDetail(DetailView):
    model = ModelProf
    context_object_name = 'modelprof_one'
    success_url = '/anketa/modelprof/'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ModelProfDetail,self).get_context_data(**kwargs)
        context['sometry'] = self.model._meta.verbose_name
        context['slovar'] = {'prof','navik'}
        context['secslovar'] = {'ball'}
        context['hidenslovar'] = {'id'}
        context['dopslovar'] = {'created_at','updated_at','created_it','updated_it','edesc','erem'}
        context['model'] = self.model
        return context

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class ModelProfCreate(CreateView):
    model = ModelProf
    context_object_name = 'modelprof_one'
    success_url = '/anketa/modelprof/'

    template_name_suffix = '_create_form'
    fields = '__all__'
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ModelProfCreate,self).get_context_data(**kwargs)
        context['sometry'] = self.model._meta.verbose_name
        context['model'] = self.model
        context['slovar'] = {'prof','navik'}
        context['secslovar'] = {'ball'}
        context['hidenslovar'] = {'id'}
        context['dopslovar'] = {'created_at','updated_at','created_it','updated_it','edesc','erem'}
        return context

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class ModelProfDelete(DeleteView):
    model = ModelProf
    success_url = '/anketa/modelprof/'

django_Generel_project/mysite/anketa/views/views_help.py
from django.shortcuts import render

# Create your views here.

django_Generel_project/mysite/anketa/templates/anketa/grazhdanin_detail.html
{% extends 'anketa/base.html' %}
{% load anketa_tags %}
{% block content %}




    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
    {% block sidebar %}
        {% include 'anketa/includes/_breadcrumb.html' %}
    {% endblock %}

        <!-- Main content -->
        <section class="content">


            <div class="col-md-10">

                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Наименование</th>
                        <th scope="col">Значение</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for name, value in grazhdanin_one.get_fields %}
                        {% if name in slovar %}
                            <tr>
                                <td>
                                    {% field_name grazhdanin_one name %}
                                </td>
                                <td>
                                    {{ value |  nonefortext }}
                                </td>
                            </tr>
                        {% endif %}
                     {% if name in secslovar %}
                            <tr>
                                <td>
                                    {% field_name grazhdanin_one name %}
                                </td>
                                <td>
                                    {{ value |  nonefortext }}
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}

                    </tbody>
                </table>

            <a href="{% url 'anketa:Grazhdanin' %}" class="btn btn-secondary float-right">
                {% my_comeback %}</a>


            </div>

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
{% endblock content %}

django_Generel_project/mysite/anketa/templates/anketa/grazhdanin_list.html
{% extends "anketa/base.html" %}

{#{% block page_heading %}{% endblock %}#}
{% block title %}{{ sometry }} {% endblock %}

{% block content %}

{% load anketa_tags %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">

    <!-- Content Header (Page header) -->
    {% block sidebar %}
    {% include 'anketa/includes/_breadcrumb.html' %}
    {% endblock %}

    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <button class="btn bg-success btn-sm">
            <a href="{% url 'anketa:GrazhdaninCreate' %}" class=''>
                Добавить новый
            </a>
        </button>
        <br><br>

        <div class="container-fluid row">
            <div class="col-md-12">
                <table class="table table-striped table-bordered ">
                    <tr>
                        <th class="w-25">{{col1name}}</th> <th class="w-25">{{col2name}}</th> <th class="w-25">{{col3name}}</th>
                        <th colspan="3">Сервисы</th>

                    </tr>

                    {% for item in grazhdanin_list %}
                    <tr>
                         <td><h5 class="card-title">{{ item.avatar }}</h5></td>  <td><h5 class="card-title">{{ item.nomer }}</h5></td>  <td><h5 class="card-title">{{ item.sertific }}</h5></td>
                        <td>
                            <button class="btn bg-primary  btn-sm">
                                <a href="{% url 'anketa:GrazhdaninUpdate' item.pk %}">Редактировать</a>
                            </button>
                        </td>
                        <td>
                            <button class="btn bg-primary  btn-sm">
                                <a href="{% url 'anketa:GrazhdaninDetail' item.pk %}">Подробнее</a>
                            </button>
                        </td>
                        <td>
                            <button class="btn bg-danger  btn-sm" >
                                <a href="{% url 'anketa:GrazhdaninDelete' item.pk %}">Удалить</a>
                            </button>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>

        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

{% endblock %}

django_Generel_project/mysite/anketa/templates/anketa/modelprof_confirm_delete.html
{% extends 'anketa/base.html' %}
{% load anketa_tags %}
{% block content %}

    <div class="content-wrapper">
            <!-- Content Header (Page header) -->
    {% block sidebar %}
    {% include 'anketa/includes/_breadcrumb.html' %}
    {% endblock %}

    <section class="content">

    <h2>Удаление</h2>
    <p>Вы точно хотите удалить?</p>
    <form method="post">
        {% csrf_token %}
        <p class="text-danger text-bold"> Удаляется обьект:  "{{ object }}"</p>
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'anketa:ModelProf' %}" class="btn btn-default">Выйти</a>
    </form>
    </section>
    </div>

{% endblock %}

django_Generel_project/mysite/anketa/templates/anketa/modelprof_list.html
{% extends "anketa/base.html" %}

{#{% block page_heading %}{% endblock %}#}
{% block title %}{{ sometry }} {% endblock %}

{% block content %}

{% load anketa_tags %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">

    <!-- Content Header (Page header) -->
    {% block sidebar %}
    {% include 'anketa/includes/_breadcrumb.html' %}
    {% endblock %}

    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <button class="btn bg-success btn-sm">
            <a href="{% url 'anketa:ModelProfCreate' %}" class=''>
                Добавить новый
            </a>
        </button>
        <br><br>

        <div class="container-fluid row">
            <div class="col-md-12">
                <table class="table table-striped table-bordered ">
                    <tr>
                        <th class="w-25">{{col1name}}</th> <th class="w-25">{{col2name}}</th> <th class="w-25">{{col3name}}</th>
                        <th colspan="3">Сервисы</th>

                    </tr>

                    {% for item in modelprof_list %}
                    <tr>
                         <td><h5 class="card-title">{{ item.prof }}</h5></td>  <td><h5 class="card-title">{{ item.navik }}</h5></td>  <td><h5 class="card-title">{{ item.ball }}</h5></td>
                        <td>
                            <button class="btn bg-primary  btn-sm">
                                <a href="{% url 'anketa:ModelProfUpdate' item.pk %}">Редактировать</a>
                            </button>
                        </td>
                        <td>
                            <button class="btn bg-primary  btn-sm">
                                <a href="{% url 'anketa:ModelProfDetail' item.pk %}">Подробнее</a>
                            </button>
                        </td>
                        <td>
                            <button class="btn bg-danger  btn-sm" >
                                <a href="{% url 'anketa:ModelProfDelete' item.pk %}">Удалить</a>
                            </button>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>

        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

{% endblock %}

django_Generel_project/mysite/anketa/templates/anketa/naviki_confirm_delete.html
{% extends 'anketa/base.html' %}
{% load anketa_tags %}
{% block content %}

    <div class="content-wrapper">
            <!-- Content Header (Page header) -->
    {% block sidebar %}
    {% include 'anketa/includes/_breadcrumb.html' %}
    {% endblock %}

    <section class="content">

    <h2>Удаление</h2>
    <p>Вы точно хотите удалить?</p>
    <form method="post">
        {% csrf_token %}
        <p class="text-danger text-bold"> Удаляется обьект:  "{{ object }}"</p>
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'anketa:Naviki' %}" class="btn btn-default">Выйти</a>
    </form>
    </section>
    </div>

{% endblock %}

django_Generel_project/mysite/anketa/templates/anketa/proffessia_confirm_delete.html
{% extends 'anketa/base.html' %}
{% load anketa_tags %}
{% block content %}

    <div class="content-wrapper">
            <!-- Content Header (Page header) -->
    {% block sidebar %}
    {% include 'anketa/includes/_breadcrumb.html' %}
    {% endblock %}

    <section class="content">

    <h2>Удаление</h2>
    <p>Вы точно хотите удалить?</p>
    <form method="post">
        {% csrf_token %}
        <p class="text-danger text-bold"> Удаляется обьект:  "{{ object }}"</p>
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'anketa:Proffessia' %}" class="btn btn-default">Выйти</a>
    </form>
    </section>
    </div>

{% endblock %}

django_Generel_project/mysite/anketa/templates/anketa/sertifikat_list.html
{% extends "anketa/base.html" %}

{#{% block page_heading %}{% endblock %}#}
{% block title %}{{ sometry }} {% endblock %}

{% block content %}

{% load anketa_tags %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">

    <!-- Content Header (Page header) -->
    {% block sidebar %}
    {% include 'anketa/includes/_breadcrumb.html' %}
    {% endblock %}

    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <button class="btn bg-success btn-sm">
            <a href="{% url 'anketa:SertifikatCreate' %}" class=''>
                Добавить новый
            </a>
        </button>
        <br><br>

        <div class="container-fluid row">
            <div class="col-md-12">
                <table class="table table-striped table-bordered ">
                    <tr>
                        <th class="w-25">{{col1name}}</th> <th class="w-25">{{col2name}}</th>
                        <th colspan="3">Сервисы</th>

                    </tr>

                    {% for item in sertifikat_list %}
                    <tr>
                         <td><h5 class="card-title">{{ item.title }}</h5></td>  <td><h5 class="card-title">{{ item.polniy }}</h5></td>
                        <td>
                            <button class="btn bg-primary  btn-sm">
                                <a href="{% url 'anketa:SertifikatUpdate' item.pk %}">Редактировать</a>
                            </button>
                        </td>
                        <td>
                            <button class="btn bg-primary  btn-sm">
                                <a href="{% url 'anketa:SertifikatDetail' item.pk %}">Подробнее</a>
                            </button>
                        </td>
                        <td>
                            <button class="btn bg-danger  btn-sm" >
                                <a href="{% url 'anketa:SertifikatDelete' item.pk %}">Удалить</a>
                            </button>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>

        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

{% endblock %}