django_Generel_project/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static

from mysite.home import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include("mysite.authentication.urls")), # Auth routes - login / register

    path('car/', include('mysite.car.urls')),  # подключение приложения
    path('helicopter/', include('mysite.helicopter.urls')),  # подключение приложения
    path('anketa/', include('mysite.anketa.urls')),  # подключение приложения
    path('testik/', include('mysite.testik.urls')),  # подключение приложения

                  # Leave `Home.Urls` as last the last line
                  # Leave `Home.Urls` as last the last line НЕ УДАЛЯТЬ $ КАК БЫ СИЛЬНО НИ ХОТЕЛОСЬ
                  # удаление этой штуки влечет за собой изменение ссылок на скачивание всех файлов
    re_path("^$", include("mysite.home.urls")),


    path('<str:template_name>.html/', views.static_html, name='temp_html')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_Generel_project/mysite/car/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static

from mysite.car.views import *
from mysite.home import views
app_name = 'car'
urlpatterns = [
    #path('admin/', admin.site.urls),
    path('mycar/', MyCarView.as_view(), name='MyCar'),
    path('mycar/update/<int:pk>/', MyCarUpdate.as_view(), name='MyCarUpdate'),
    path('mycar/detail/<int:pk>/', MyCarDetail.as_view(), name='MyCarDetail'),
    path('mycar/create/', MyCarCreate.as_view(), name='MyCarCreate'),
    path('mycar/delete/<int:pk>/', MyCarDelete.as_view(), name='MyCarDelete'),
]

django_Generel_project/mysite/car/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Forlog(models.Model):
    created_at = models.DateTimeField(auto_now_add=True,  verbose_name='Создано')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обновлено')
    edesc = models.TextField(blank=True, null=True, verbose_name='Комментарий')
    erem = models.BooleanField(default=False, verbose_name='Удалить?')

    class Meta:
        abstract = True

###########################################################################################

class MyCar(Forlog):
    name = models.CharField(max_length=255, blank=False, null= False, default="Машинка", verbose_name="Название")
    color = models.CharField(max_length=255, blank=False, null = False, default="Черный", verbose_name="Цвет")
    nomb = models.CharField(max_length=255, blank=False, null = False, default="TO123P", verbose_name="Номер")

    def str(self):
        return self.name

    class Meta:
        verbose_name = 'Машинка'
        verbose_name_plural = 'Машинки'
        ordering = ['id']

    def get_absolute_url(self):
        return reverse('car', kwargs={"slug": self.pk})

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in MyCar._meta.fields]

django_Generel_project/mysite/car/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DeleteView, CreateView, DetailView, UpdateView, ListView

from mysite.car.models import MyCar

item_for_page =15

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class MyCarView(ListView):
	model = MyCar
	context_object_name = 'mycar_list'
	success_url = reverse_lazy('car: MyCar')

	paginate_by = item_for_page
	def get_context_data(self, *, object_list=None, **kwargs):
		context = super(MyCarView,self).get_context_data(**kwargs)
		context['sometry'] = self.model._meta.verbose_name_plural
		context['col1name'] = self.model._meta.get_field("name").verbose_name
		context['col2name'] = self.model._meta.get_field("color").verbose_name
		context['col3name'] = self.model._meta.get_field("nomb").verbose_name
		context['collastname'] = 'Cервисы'
		return context

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class MyCarUpdate(UpdateView):
	model = MyCar
	template_name_suffix = '_update_form'
	fields = '__all__'
	success_url = '/car/mycar/'

	def get_context_data(self, *, object_list=None, **kwargs):
		context = super(MyCarUpdate,self).get_context_data(**kwargs)
		context['sometry'] = self.model._meta.verbose_name
		context['slovar'] = {'name','color'}
		context['secslovar'] = {'nomb'}
		context['hidenslovar'] = {'id'}
		context['dopslovar'] = {'updated_at','erem','edesc','created_at'}
		context['model'] = self.model
		return context

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class MyCarDetail(DetailView):
	model = MyCar
	context_object_name = 'mycar_one'
	success_url = '/car/mycar/'

	def get_context_data(self, *, object_list=None, **kwargs):
		context = super(MyCarDetail,self).get_context_data(**kwargs)
		context['sometry'] = self.model._meta.verbose_name
		context['slovar'] = {'name','color'}
		context['secslovar'] = {'nomb'}
		context['hidenslovar'] = {'id'}
		context['dopslovar'] = {'updated_at','erem','edesc','created_at'}
		context['model'] = self.model
		return context

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class MyCarCreate(CreateView):
	model = MyCar
	context_object_name = 'mycar_one'
	success_url = '/car/mycar/'

	template_name_suffix = '_create_form'
	fields = '__all__'
	def get_context_data(self, *, object_list=None, **kwargs):
		context = super(MyCarCreate,self).get_context_data(**kwargs)
		context['sometry'] = self.model._meta.verbose_name
		context['model'] = self.model
		context['slovar'] = {'name','color'}
		context['secslovar'] = {'nomb'}
		context['hidenslovar'] = {'id'}
		context['dopslovar'] = {'updated_at','erem','edesc','created_at'}
		return context

@method_decorator(login_required(login_url='/login/'), name='dispatch')
class MyCarDelete(DeleteView):
	model = MyCar
	success_url = '/car/mycar/'

django_Generel_project/mysite/car/templates/car/base.html
{% extends "layouts/base.html" %}
{% load static %}

{% block title %} Справочники {% endblock %}

<!-- Element injected in the BODY element -->
{% block body_class %} sidebar-mini {% endblock body_class %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ ASSETS_ROOT }}/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ ASSETS_ROOT }}/css/adminlte.min.css">

{% endblock stylesheets %}

{% block content %}

{% endblock content %}


<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

    <!-- jQuery -->
    <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
{#    <script src="{% static 'assets/plugins/jquery/jquery.min.js' %}"></script>#}

    <!-- Bootstrap 4 -->
    <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/static/assets/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/static/assets/js/demo.js"></script>

{% endblock javascripts %}

django_Generel_project/mysite/car/templates/car/mycar_confirm_delete.html
{% extends 'car/base.html' %}
{% load car_tags %}
{% block content %}

    <div class="content-wrapper">
            <!-- Content Header (Page header) -->
    {% block sidebar %}
    {% include 'car/includes/_breadcrumb.html' %}
    {% endblock %}

    <section class="content">

    <h2>Удаление</h2>
    <p>Вы точно хотите удалить?</p>
    <form method="post">
        {% csrf_token %}
        <p class="text-danger text-bold"> Удаляется обьект:  "{{ object }}"</p>
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'car:MyCar' %}" class="btn btn-default">Выйти</a>
    </form>
    </section>
    </div>

{% endblock %}

django_Generel_project/mysite/car/templates/car/mycar_create_form.html
{% extends 'car/base.html' %}
{% load car_tags %}
{% block content %}




    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        {% block sidebar %}
            {% include 'car/includes/_breadcrumb.html' %}
        {% endblock %}

        <!-- Main content -->
        <section class="content">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="row">
                    <div class="col-md-6">
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Основные сведения</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                            title="Collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                {% for field in form %}
                                    <div class="form-group">
                                        {% if field.name in slovar %}
                                            {{ field.label_tag }}
                                            {{ field | addclassrow:"form-control " }}
                                            {{ field.errors }}
                                        {% endif %}
                                    </div>
                                {% endfor %}


                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <div class="col-md-6">
                        <div class="card card-secondary">
                            <div class="card-header">
                                <h3 class="card-title">Дополнительные сведения</h3>
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                            title="Collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                {% for field in form %}
                                    <div class="form-group">
                                        {% if field.name in secslovar %}
                                            {{ field.label_tag }}
                                            {{ field | addclassrow:"form-control " }}
                                            {{ field.errors }}
                                        {% endif %}
                                    </div>
                                {% endfor %}

                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->

                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <div class="card card-info collapsed-card">
                            <div class="card-header">
                                <h3 class="card-title">Дополнительная информация</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                            title="Collapse">
                                        <i class="fas fa-plus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                {% for field in form %}
                                    <div class="form-group">
                                        {% if field.name in dopslovar %}
                                            {{ field.label_tag }}
                                            {{ field | addclassrow:"form-control " }}
                                            {{ field.errors }}
                                        {% endif %}

                                    </div>
                                {% endfor %}

                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->

                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <a href="{% url 'car:MyCar' %}" class="btn btn-secondary float-right">
                            {% my_notsave %}</a>
                        <input type="submit" value="{% my_save %}" class="btn btn-success ">
                    </div>
                </div>
                <!-- /.row -->
            </form>

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
{% endblock content %}

django_Generel_project/mysite/car/templates/car/mycar_detail.html
{% extends 'car/base.html' %}
{% load car_tags %}
{% block content %}




    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
    {% block sidebar %}
        {% include 'car/includes/_breadcrumb.html' %}
    {% endblock %}

        <!-- Main content -->
        <section class="content">


            <div class="col-md-10">

                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Наименование</th>
                        <th scope="col">Значение</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for name, value in mycar_one.get_fields %}
                        {% if name in slovar %}
                            <tr>
                                <td>
                                    {% field_name mycar_one name %}
                                </td>
                                <td>
                                    {{ value |  nonefortext }}
                                </td>
                            </tr>
                        {% endif %}
                     {% if name in secslovar %}
                            <tr>
                                <td>
                                    {% field_name mycar_one name %}
                                </td>
                                <td>
                                    {{ value |  nonefortext }}
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}

                    </tbody>
                </table>

            <a href="{% url 'car:MyCar' %}" class="btn btn-secondary float-right">
                {% my_comeback %}</a>


            </div>

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
{% endblock content %}

django_Generel_project/mysite/car/templates/car/mycar_list.html
{% extends "car/base.html" %}

{#{% block page_heading %}{% endblock %}#}
{% block title %}{{ sometry }} {% endblock %}

{% block content %}

{% load car_tags %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">

    <!-- Content Header (Page header) -->
    {% block sidebar %}
    {% include 'car/includes/_breadcrumb.html' %}
    {% endblock %}

    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <button class="btn bg-success btn-sm">
            <a href="{% url 'car:MyCarCreate' %}" class=''>
                Добавить новый
            </a>
        </button>
        <br><br>

        <div class="container-fluid row">
            <div class="col-md-12">
                <table class="table table-striped table-bordered ">
                    <tr>
                        <th class="w-10">{{ col1name }}</th>
                        <th class="w-25">{{ col2name }}</th>
                        <th class="w-25">{{ col3name }}</th>
                        <th colspan="3">Сервисы</th>

                    </tr>

                    {% for item in mycar_list %}
                    <tr>
                        <td>
                            <h5 class="card-title">
                                {{ item.name }}
                            </h5>
                        </td>
                        <td>
                            <h5 class="card-title">
                                {{ item.color }}
                            </h5>
                        </td>
                        <td>
                            <h5 class="card-title">
                                {{ item.nomb }}
                            </h5>
                        </td>
                        <td>
                            <button class="btn bg-primary  btn-sm">
                                <a href="{% url 'car:MyCarUpdate' item.pk %}">Редактировать</a>
                            </button>
                        </td>
                        <td>
                            <button class="btn bg-primary  btn-sm">
                                <a href="{% url 'car:MyCarDetail' item.pk %}">Подробнее</a>
                            </button>
                        </td>
                        <td>
                            <button class="btn bg-danger  btn-sm" >
                                <a href="{% url 'car:MyCarDelete' item.pk %}">Удалить</a>
                            </button>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>

        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

{% endblock %}

django_Generel_project/mysite/car/templates/car/mycar_update_form.html
{% extends 'car/base.html' %}
{% load car_tags %}
{% block content %}




    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        {% block sidebar %}
            {% include 'car/includes/_breadcrumb.html' %}
        {% endblock %}

        <!-- Main content -->
        <section class="content">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="row">
                    <div class="col-md-6">
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Основные сведения</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                            title="Collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                {% for field in form %}
                                    <div class="form-group">
                                        {% if field.name in slovar %}
                                            {{ field.label_tag }}
                                            {{ field | addclassrow:"form-control " }}
                                            {{ field.errors }}
                                        {% endif %}
                                    </div>
                                {% endfor %}


                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <div class="col-md-6">
                        <div class="card card-secondary">
                            <div class="card-header">
                                <h3 class="card-title">Дополнительные сведения</h3>
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                            title="Collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                {% for field in form %}
                                    <div class="form-group">
                                        {% if field.name in secslovar %}
                                            {{ field.label_tag }}
                                            {{ field | addclassrow:"form-control " }}
                                            {{ field.errors }}
                                        {% endif %}
                                    </div>
                                {% endfor %}

                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->

                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <div class="card card-info collapsed-card">
                            <div class="card-header">
                                <h3 class="card-title">Дополнительная информация</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                            title="Collapse">
                                        <i class="fas fa-plus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                {% for field in form %}
                                    <div class="form-group">
                                        {% if field.name in dopslovar %}
                                            {{ field.label_tag }}
                                            {{ field | addclassrow:"form-control " }}
                                            {{ field.errors }}
                                        {% endif %}

                                    </div>
                                {% endfor %}

                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->

                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <a href="{% url 'car:MyCar' %}" class="btn btn-secondary float-right">
                            {% my_notsave %}</a>
                        <input type="submit" value="{% my_save %}" class="btn btn-success ">
                    </div>
                </div>
                <!-- /.row -->
            </form>

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
{% endblock content %}